### ISSUE TITLE
Файлы настроек отличаются на разных языках

### ISSUE THREAD

**Issue by glossyweb** [doevent/facebook-auto-liker#1]
Файлы настроек отличаются на разных языках. + En версия не отправляет уведомления в telegram

**Comment by doevent** [comment]
Отличие настроек, что для EN версии нет планировщика. Для RU версии тоже не планирую его поддерживать, так как стал пользоваться встроенным Windows Task Scheduler.

**Comment by doevent** [comment]
> Файлы настроек отличаются на разных языках. + En версия не отправляет уведомления в telegram

Отличие настроек, что для EN версии нет планировщика. Для RU версии тоже не планирую его поддерживать, так как стал пользоваться встроенным Windows Task Scheduler.
